# Generated by Django 3.1.2 on 2021-01-08 14:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_auto_20210106_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
    ]
